#!/bin/bash
#
#
####################################################################################
# script che recupera i podcast del radio giornale della Sardegna   
#
# v:1.0                                                                    
#
# dipendenze: curl,jq,cat,wget
#
#
####################################################################################


# set global variable

grrAPI="https://www.rainews.it/dl/rai24/tgr/basic/archivio/ContentSet-49e9a5dc-a10a-47ee-bb5c-42c3879c2e71.json"

ag="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/56.0"

# remove old jason data
rm ./data/Sardegna.json

# get  jason data
curl -A "$ag"  "$grrAPI" -o data/Sardegna.json
echo " "
echo "get data api... done!"
echo " "

# extract jason data of the 2 last  podcast stored
data0=`cat ./data/Sardegna.json | jq -r '.items[0]|.date'`
Media0=`cat ./data/Sardegna.json | jq -r '.items[0]|.mediaUrl'`
ora0=`cat ./data/Sardegna.json | jq -r '.items[0]|.title'`

data1=`cat ./data/Sardegna.json | jq -r '.items[1]|.date'`
Media1=`cat ./data/Sardegna.json | jq -r '.items[1]|.mediaUrl'`
ora1=`cat ./data/Sardegna.json | jq -r '.items[1]|.title'`

# extract time onair podcast "h_m"
Ora0=`echo $ora0 | sed -e 's/\ /\n/g' | grep ":"| sed -e 's/\:/\_/g'`

Ora1=`echo $ora1 | sed -e 's/\ /\n/g' | grep ":"| sed -e 's/\:/\_/g'`

# extract date onair podcast "type 10-10-2020"
Data0=`echo $data0  | sed -e 's/\//\-/g'`
Data1=`echo $data1  | sed -e 's/\//\-/g'`

echo " "
echo "extract data... done!"
echo " "

# download podcast

wget -d -c -U "$ag" "$Media0" -O GRR_Sardegna_"$Data0"_"$Ora0".mp3
wget -d -c -U "$ag" "$Media1" -O GRR_Sardegna_"$Data1"_"$Ora1".mp3