#!/bin/bash
#
#
####################################################################################
# script che recupera l'ultimo podcast di https://www.raiplaysound.it/programmi/primapagina 
#
# V:2.0  alpha_debug_mode  18 DICEMBRE 2021                                                        
#
# dipendenze: curl,jq,cat,wget
# uso: lancia lo script "R3_primapagina" per scaricare l'ultimo podcast inserito
# log: modifiche per cambio api e dominio rai
####################################################################################

# set global variable

primapaginaapi="https://www.raiplaysound.it/programmi/primapagina.json"
grbase="https://www.raiplaysound.it"
ag="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/56.0"


# remove old jason data
rm ./data/primapagina.json
#rm ./data/Lprimapagina.json


# get  jason data
curl -A "$ag"  "$primapaginaapi" -o data/primapagina.json
echo " "
echo " "
echo "get data api... done!"
echo " "


# extract jason data of the last podcast

dataT=`cat ./data/primapagina.json | jq -r '."block" | ."cards" | .[0] | ."downloadable_audio" | ."title"'`

echo " "
echo "extract data... find.."
echo " "
echo " "
echo podcast_title: $dataT
echo " "



Lpodcast=`cat ./data/primapagina.json | jq -r '."block" | ."cards" | .[0] | ."downloadable_audio" | ."url"'`

echo " "
echo podcast_url: $Lpodcast
echo " "


# extract time and date  onair podcast 

ora=`cat ./data/primapagina.json | jq -r '."block" | ."cards" | .[0] | ."create_time"'`
Ora=`echo $ora | sed -e 's/\ /\n/g' | grep ":"| sed -e 's/\:/\_/g'`

data=`cat ./data/primapagina.json | jq -r '."block" | ."cards" | .[0] | ."create_date"'`
Data=`echo $data | sed -e 's/\//\-/g'`

echo " "
echo log_podcast_creation: $Data $Ora
echo " "
echo " "

# download podcast
echo " download podcast.. opus_encode.."
echo " "
wget -d -c -U "$ag" "$Lpodcast" -O primapagina_"$Data"_"$Ora".mp3

# encode audio data... small file

#ffmpeg -n -i primapagina_"$Data"_"$Ora".mp3 -vn -acodec aac -ab 64k -ac 1 primapagina_"$Data"_"$Ora".m4a

ffmpeg -n -i primapagina_"$Data"_"$Ora".mp3 -acodec libopus -b:a 40k -ac 1 primapagina_"$Data"_"$Ora".opus

#ffmpeg -n -i primapagina_"$Data"_"$Ora".mp3 -vn -acodec libvorbis -aq 1 -ac 1 primapagina_"$Data"_"$Ora".ogg

rm primapagina_"$Data"_"$Ora".mp3
